#!/bin/bash
# for CAPSLOCK DAY!!!

cat - | awk '
 $2 == "PRIVMSG" {
  split(substr($1,2), b, "!")
  from = b[1]
  host = b[2]
  to = $3
  msg = substr($0, index(substr($0,2), ":") + 1)

  if( from != toupper(from) ) print "KICK " to " " from " LOWERCASE NICK"
  if( msg != toupper(msg) ) print "KICK " to " " from " LOWERCASE MSG"

 }
' >> .ctl
